from seq1 import Seq
print("-----| Practice 1, Exercise 5 |------")
s1 = Seq()
s2 = Seq("ACTGA")
s3 = Seq("Invalid sequence")
print(f"Sequence 1:(Length: {s1.len()})", s1.strbases)
print(s1.count_base(s1.strbases))
print(f"Sequence 2: (Length: {s2.len()})", s2.strbases)
print(s2.count_base(s2.strbases))
print(f"Sequence 3: (Length: {s3.len()})", s3.strbases)
print(s3.count_base(s3.strbases))